### ISSUE TITLE
[!] Error installing GData Cocoapods

### ISSUE THREAD

**Issue by AaoIi** [google/gdata-objectivec-client#206]
Im facing a problem with integrating GData into my project in anyway to use GooglePicasaAPI and Auth2 in my project. i tried importing the Library manually its just impossible even with its dependencies. so here is the error i got when trying to install it using Cocoapods, any help ? Thank you :)

`pod 'GData'
`

> pod install
> Analyzing dependencies
> Downloading dependencies
> Installing GData (1.12.0)
> 
> [!] Error installing GData
> [!] /usr/bin/svn export --non-interactive --trust-server-cert --force http://gdata-objectivec-client.googlecode.com/svn/tags/gdata-objectivec-client-1.12.0 /var/folders/2r/cj9jtc2s37s3x4wl5c7vmr9r0000gn/T/d20171020-13167-n9vvkh
> 
> svn: E170013: Unable to connect to a repository at URL 'http://gdata-objectivec-client.googlecode.com/svn/tags/gdata-objectivec-client-1.12.0'
> svn: E160013: '/svn/tags/gdata-objectivec-client-1.12.0' path not found
>

**Comment by thomasvl** [comment]
We don't maintain that pod (we don't actually control a pod for GData), so you'll need to reach out to the owner of the pod: https://cocoapods.org/pods/GData

**Comment by AaoIi** [comment]
@thomasvl, There is no way to contact them through cocoapods site, the authors are "The Google Data APIs team" and its maintained by "Fl0p". its just a dead-end for me.

**Comment by thomasvl** [comment]
"Authors" are for the code, that's us.  But your problems is completely around the cocoapod, and that's "Fl0p".  You can get the info from pod's commandline:

```
$ pod trunk info GData

GData
    - Versions:
      - 0.0.1 (2014-05-19 21:49:54 UTC)
      - 1.12.0 (2014-05-19 21:57:25 UTC)
      - 1.9.1 (2014-05-19 21:43:31 UTC)
      - 1.9.999 (2014-05-19 21:43:52 UTC)
      - 2.0.0 (2014-05-19 21:43:31 UTC)
    - Owners:
      - Fl0p <serg.flop@gmail.com>
```

Try that address.

**Comment by pjl1234567** [comment]
@AaoIi Have you solved your problem?

**Comment by AaoIi** [comment]
@pjl1234567 To be honest no, because even the pod owner "Fl0p" respond ones and never again when i asked him to add me or pass on the code so i will be able to maintain it.

**Comment by pjl1234567** [comment]
@AaoIi   Oh  I know,I know,I've  solved it.Can't use pod( @thomasvl said "  We don't maintain that pod (we don't actually control a pod for GData)" ).  You should download the soure code(gdata-objectivec-client).But it can't run .Because there are two files missing.You should download them(https://github.com/google/gtm-session-fetcher    and  https://github.com/google/gtm-oauth2)  ,and put them under the correspoding directory.  (gdata-objectivec-client/Deps/gtm-session-fetcher   and  gdata-objectivec-client/Deps/gtm-oauth2).   So the program can run,and generate some framework.the framework is what you want.

**Comment by AaoIi** [comment]
Now its running at least, Thanks everyone :)
